### ISSUE TITLE
Breaks hide lines feature of mdbook

### ISSUE THREAD

**Issue by ashishkujoy** [MR-Addict/mdbook-repl#1]
mdbook provide a feature to hide some line from code block. As explained [here](https://rust-lang.github.io/mdBook/format/mdbook.html#hiding-code-lines) . I am trying to use mdbook-repl preprocessor to have some javascript example in my book. But mdbook-repl is making the code line visible.

book.toml
```
[book]
authors = []
language = "en"
multilingual = false
src = "src"
title = "Javascript"

[preprocessor.repl]
# iframe url
src = "https://mr-addict.github.io/mdbook-repl/embed/"

# enable javascript repl and lazy loading
javascript.enable = true
javascript.loading = "lazy"

[output.html.code.hidelines]
javascript = "~"
```

markdown from chapter
```javascript
~const somefunction = () => {
    console.log(3 + 4);
~}
```

Expected view(this is without javascript.enable = true)
<img width="787" alt="Screenshot 2024-04-06 at 10 55 52 PM" src="https://github.com/MR-Addict/mdbook-repl/assets/34642693/d3e3f186-13ee-4f17-9a54-59e6820022a1">

Actual view(with javascript.enable = true)
<img width="781" alt="Screenshot 2024-04-06 at 10 56 44 PM" src="https://github.com/MR-Addict/mdbook-repl/assets/34642693/f4c4f346-59d2-4b7c-83c4-a040ec02ead1">

**Comment by MR-Addict** [comment]
Thank you for your feedback. I'm glad that my project helps you.

I don't know this mdbook trick before. However I don't know that is it actually necessary to include this feature. Because you can just remove these lines in your codeblock rather than using a prefix to hide it.

I'll take a consideration and do some experiments. Tell me if you do need this feature, I can create a new release based for it.

**Comment by ashishkujoy** [comment]
Yes this feature is quite useful. At multiple places I want to hide some code and only keep an important section of code visible to the reader. This use case usually occur when showing some incremental changes for a function.
At each step reader need to see code running. If some part is removed from code block, it may not run as aspected.

**Comment by MR-Addict** [comment]
Okay then I'll create a new release about it.

Feel free to tell me if you have any other questions or suggestions.

**Comment by MR-Addict** [comment]
I have create a new release about it, you can check it out [here](https://github.com/MR-Addict/mdbook-repl/releases/tag/0.2.4).

**Comment by ashishkujoy** [comment]
Thanks for the feature.
