### ISSUE TITLE
Feature Request: Option to disable repl for a code block

### ISSUE THREAD

**Issue by ashishkujoy** [MR-Addict/mdbook-repl#2]
mdbook has a feature to disable code run a block of rust code see [here](https://rust-lang.github.io/mdBook/format/mdbook.html#rust-playground) it would be great have a similar feature with mdbook-repl

**Comment by MR-Addict** [comment]
What you mean is able to disable repl for a specific codeblock?

Actually you can do this in mdbook-repl, [mdbook repl options](https://mr-addict.github.io/mdbook-repl/usage.html#options).

I'm sorry that the docs are not clear enough.

**Comment by ashishkujoy** [comment]
Thanks @MR-Addict for the prompt reply. I missed that option.
