### ISSUE TITLE
Support for hidden lines

### ISSUE THREAD

**Issue by maebli** [MR-Addict/mdbook-repl#3]
Would be nice if the hidden python code was runnable

https://rust-lang.github.io/mdBook/format/mdbook.html?highlight=ANCHOR#hiding-code-lines

**Comment by MR-Addict** [comment]
In this real time playground scenario, I think this is not an necessary feature.

There may be some some conflicts between hidden lines and editable content which makes it hard to implement. Also, in mdbook rust playground, hidden lines and editable content are not support at the same time.

A compromise way is to make hidden lines runnable only in **readonly** mode. Let me know your opinion about this.

> Tips:
>
> If you find all of your python code blocks are rendered by preprocessor, you can use [nprepl](https://mr-addict.github.io/mdbook-repl/usage.html#options) option tag.

**Comment by maebli** [comment]
Hm i see, I thought it was supported by playground but on second thoughts I can see the issue of editing. My use case is basically I have some libs that are few pages long of generated code and I want to just run an example.  Perhapse I can somehow use micropip to include the package privately?
